### ISSUE TITLE
ContentNegotiatingViewResolver not supported.

### ISSUE THREAD

**Issue by wrey75** [sps/mustache-spring-view#15]
Basically, the Spring Dispatcher authorizes the use of dispatching by contents. Unfortunately, your library does not support this because there is a FileNotFoundException raised when the template is not present. Then the Spring dispatcher is stopped and the other viewers have no chance to do be called.

I rewritten your code based on the Freemarker code available. I needed to do some changes, not very pretty but I think full compatible as I had success to run the modified code.

The MustacheView has changed a lot due to the copy/paste of code used in FreeMarker and then, I put the stuff (compiler, template and loader) directly in the view.

**Comment by travi** [comment]
Is there any update on this issue?

**Comment by sps** [comment]
Closing as stale. Please re-open if needed.
