### ISSUE TITLE
cache doesn't effect?

### ISSUE THREAD

**Issue by zhengzhiqiang** [sps/mustache-spring-view#22]
hello,when i set the property 'cache' false,it doen't effect.I find it get template from cache always.is it?

**Comment by YacheLee** [comment]
I have the same issue...
hope anyone can give some hints...

**Comment by zhengzhiqiang** [comment]
I found that,cache does't effect because except spring-view,mustache framework has cache also.So you need remove mustache cache by rewrite DefaultMustacheFactory in develop.I do it like so:
protected LoadingCache<String, Mustache> createMustacheCache() {
        //one seconds expire
        return CacheBuilder.newBuilder().expireAfterWrite(1, TimeUnit.SECONDS).build(new MustacheCacheLoader());
    }

**Comment by YacheLee** [comment]
Thank you!
It's very helpful for me to develop using mustache~~~
